"""Add Mountain and Trail tables

Revision ID: baa3eb85a0b6
Revises: e40314651d5f
Create Date: 2026-08-06 11:01:15.499864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa3eb85a0b6'
down_revision: Union[str, None] = 'e40314651d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mountain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('elevation', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mountain_id'), 'mountain', ['id'], unique=False)
    op.create_index(op.f('ix_mountain_name'), 'mountain', ['name'], unique=False)
    op.create_table('trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mountain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mountain_id'], ['mountain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trail_id'), 'trail', ['id'], unique=False)
    op.create_index(op.f('ix_trail_name'), 'trail', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trail_name'), table_name='trail')
    op.drop_index(op.f('ix_trail_id'), table_name='trail')
    op.drop_table('trail')
    op.drop_index(op.f('ix_mountain_name'), table_name='mountain')
    op.drop_index(op.f('ix_mountain_id'), table_name='mountain')
    op.drop_table('mountain')
    # ### end Alembic commands ###
